[workspace]
version = "1.2.2"
firsttime = false
current_exercise = "02_data_structures/data_structures4.py"

[theme]
name = "default"
GREEN = "bold green"
RED = "bold red"
ORANGE = "bold orange"
LIGHT_BLUE = "bold lightblue"
BACKGROUND = "#1e1e2e"
